import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ApolloWrapper from "@/ApolloWrapper/ApolloWrapper";
import { CartProvider } from "@/components/Cart/useCart";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <ApolloWrapper>
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </ApolloWrapper>
        </CartProvider>
      </body>
    </html>
  );
}
